FROM prom/prometheus:v2.45.0

# Copia la configurazione di scraping
COPY ./prometheus/prometheus.yml /etc/prometheus/prometheus.yml

# Imposta la directory di lavoro e i permessi corretti per il volume dati
WORKDIR /prometheus

EXPOSE 9090

CMD [ "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--storage.tsdb.retention.time=15d" ]
